<?php
    $collection = $block->getEditData();
?>
<div id="custom-form">
   <form class="contact custom" 
         action="<?php echo $this->getUrl('weather/index/save', ['_secure' => true]);?>"
         id="custom-form"
         method="post"
         data-hasrequired="<?php  echo __('* Required Fields') ?>"
         data-mage-init='{"validation":{}}'>
 
       <input type="hidden" name="editId" id="editId" value="<?= $collection['id']; ?>" />
 
        <fieldset class="fieldset">
            <legend class="legend"><span><?php  echo __("city") ?></span></legend><br />
            <div class="field name required">
                <label class="label" for="name"><span><?php  echo __('City') ?></span></label>
                <div class="control">
                    <input name="name" id="name" title="<?php  echo __('City') ?>" value="<?= $collection['id']; ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
           
        </fieldset>
    
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php  echo __('Submit') ?>" class="action submit primary" id="custom_btn">
                    <span><?php  echo __('Submit') ?></span>
                </button>
            </div>
        </div>
   </form>
</div>