

<?php
/**
 * @var \Sign\Test\Block\Vista $block
 */
$list = $block->getPostCollection();
$lastItem = $list->getLastItem();
$lastfilt =  $lastItem->getData()["filt"];
$lastfrom =  $lastItem->getData()["from"];
$lastto = $lastItem->getData()["to"];
echo $lastfilt;
?>

<div id="custom-form">
   <form class="contact custom"
         action="<?php echo $this->getUrl('weather/index/index', ['_secure' => true]);?>"
         id="custom-form"
         method="post"
         data-hasrequired="<?php  echo __('* Required Fields') ?>"
         data-mage-init='{"validation":{}}'>

        <fieldset class="fieldset">
            
            <div class="field name required formWidth">
                <label class="label" for="filt"><span><?php  echo __('City') ?></span></label>
                <div class="control">
                    <input name="filts" id="filts" title="<?php  echo __('City') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field name required formWidth">
            <label class="label" for="city"><span><?php  echo __('Date From') ?></span></label>
                <div class="control">
                    <input name="froms" id="froms" title="<?php  echo __('Date From') ?>" class="input-text" type="date" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field name required formWidth">
            <label class="label" for="city"><span><?php  echo __('Date To') ?></span></label>
                <div class="control">
                    <input name="tos" id="tos" title="<?php  echo __('Date To') ?>" class="input-text" type="date" data-validate="{required:true}"/>
                </div>
            </div>
        </fieldset>
	

        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php  echo __('Submit') ?>" class="action submit primary" id="custom_btn">
                    <span><?php  echo __('show Histroy') ?></span>
                </button>
              
        </div>
   </form>
</div>
<div id="custom-form" class="myForm">
   <form class="contact custom"
         action="<?php echo $this->getUrl('weather/index/index', ['_secure' => true]);?>"
         id="custom-form"
         method="get"
         data-hasrequired="<?php  echo __('* Required Fields') ?>"
         data-mage-init='{"validation":{}}'>
	

        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="convert" id="convert" value="helooo" />
                <button type="submit" title="<?php  echo __('Submit') ?>" class="action submit primary" id="custom_btn">
                    <span><?php  echo __('To PDF') ?></span>
                </button>
            </div>
        </div>
   </form>
</div>


<style>
    .formWidth{
        width: 150px;
    }
    .myForm{
        padding: 10px;
    }
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}
</style>

<table>
    <tr>
        <th >City</th>
        <th >Country</th>
        <th>Description</th>
        <th >Temperature</th>
        <th >Feels Like</th>
        <th>Pressure</th>
        <th>Humidity</th>
        <th >Wind Speed</th>
        <th >Sunrise</th>
        <th>Sunset</th>
        <th>Date</th>
    </tr>
    <?php

       


    $mypr = $block->getTown('tbilisi');
    echo $mypr;
    $bi = json_decode("$mypr");
    echo $bi->cod;

  
    
    // if(isset($_POST["convert"])){
        
    //     $pdf = new \Zend_Pdf(); //Create new PDF file

    //     $page = $pdf->newPage(\Zend_Pdf_Page::SIZE_A4);
        
    //     $pdf->pages[] = $page; 
        
    //     $page->setFont(\Zend_Pdf_Font::fontWithName(\Zend_Pdf_Font::FONT_HELVETICA), 20);  //Set Font 
        
    //     $page->drawText($city, 100, 510); 
        
    //     $pdfData = $pdf->render(); // Get PDF document as a string 
        
    //     header("Content-Disposition: inline; filename=result.pdf"); 
        
    //     header("Content-type: application/x-pdf"); 
        
    //     echo $pdfData; 
        
    // };

   


    foreach ($block->getPostCollection() as $key=>$post){
        if($post->getCity() === $lastfilt && $lastfrom <= $post->getReport() && $post->getReport() <= $lastto){
            
            echo '<tr>
            <td>'.$post->getCity().'</td>
            <td>'.$post->getCountry().'</td>
            <td>'.$post->getDescription().'</td>
            <td>'.$post->getTemperature().'</td>
            <td>'.$post->getFeels_Like().'</td>
            <td>'.$post->getPressure().'</td>
            <td>'.$post->getHumidity().'</td>
            <td>'.$post->getWind().'</td>
            <td>'.$post->getSunrise().'</td>
            <td>'.$post->getSunset().'</td>
            <td>'.$post->getReport().'</td>
          </tr>';
        }
        
      
    }
   
    ?>
</table>
