<div id="custom-form">
   <form class="contact custom"
         action="<?php echo $this->getUrl('weather/index/save', ['_secure' => true]);?>"
         id="custom-form"
         method="post"
         data-hasrequired="<?php  echo __('* Required Fields') ?>"
         data-mage-init='{"validation":{}}'>

        <fieldset class="fieldset">
            
            <div class="field name required">
                <label class="label" for="city"><span><?php  echo __('City') ?></span></label>
                <div class="control">
                    <input name="city" id="city" title="<?php  echo __('City') ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
        </fieldset>
		<fieldset class="fieldset">
            
            <div class="field name required">
                <label class="label" for="date_from"><span><?php  echo __('Date From') ?></span></label>
                <div class="control">
                    <input name="date_from" id="date_from" title="<?php  echo __('Date From') ?>" class="input-text" type="date" data-validate="{required:true}"/>
                </div>
            </div>
			<div class="field name required">
                <label class="label" for="date_to"><span><?php  echo __('Date To') ?></span></label>
                <div class="control">
                    <input name="date_to" id="date_to" title="<?php  echo __('Date To') ?>" class="input-text" type="date" data-validate="{required:true}"/>
                </div>
            </div>
        </fieldset>

        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php  echo __('Submit') ?>" class="action submit primary" id="custom_btn">
                    <span><?php  echo __('show Histroy') ?></span>
                </button>
            </div>
        </div>
   </form>
</div>

<?php
/**
 * @var \Sign\Test\Block\Vista $block
 */
?>

<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #dddddd; }
    .post-id{width:2%} .post-name{width:30%}
</style>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Title</th>
        <th>Content</th>
    </tr>
    <?php
    foreach ($block->getPostCollection() as $key=>$post){
        echo '<tr>
                    <td>'.$post->getPostId().'</td>
                    <td>'.$post->getName().'</td>
                    <td>'.$post->getDate().'</td>
                  </tr>';
    }
    ?>
